"""
Google Imagen Adapter for Tal - Social Media Brain.

Uses Google's GenAI SDK with Imagen 4 for image generation.
"""

import logging
import os
from io import BytesIO
from typing import Optional

from PIL import Image

from adapters.nanobanana import (
    GenerationRequest,
    GenerationResult,
    ImageGeneratorAdapter,
)

logger = logging.getLogger(__name__)


class GoogleImagenAdapter(ImageGeneratorAdapter):
    """
    Adapter for Google's Imagen via the GenAI SDK.

    Uses the google-genai package with Imagen 4 for high-quality image generation.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: str = "imagen-4.0-generate-001",
        dry_run: bool = False,
    ):
        """
        Initialize the Google Imagen adapter.

        Args:
            api_key: Google API key. If None, reads from GOOGLE_API_KEY env var.
            model_name: Imagen model to use
            dry_run: If True, use placeholder generation
        """
        self.api_key = api_key or os.environ.get("GOOGLE_API_KEY")
        self.model_name = model_name
        self.dry_run = dry_run
        self._client = None

        logger.info(
            f"GoogleImagenAdapter initialized "
            f"(model={model_name}, dry_run={dry_run}, has_key={bool(self.api_key)})"
        )

    def _init_client(self):
        """Initialize the Google GenAI client lazily."""
        if self._client is not None:
            return

        try:
            from google import genai

            self._client = genai.Client(api_key=self.api_key)
            logger.info(f"Google GenAI client initialized with model: {self.model_name}")
        except Exception as e:
            logger.error(f"Failed to initialize Google GenAI client: {e}")
            raise

    def is_available(self) -> bool:
        """Check if the API is properly configured."""
        if self.dry_run:
            return False
        if not self.api_key:
            return False
        return True

    def generate(self, request: GenerationRequest) -> GenerationResult:
        """Generate an image using Google Imagen."""
        logger.info(f"Generation request: {request.prompt[:100]}...")

        if self.dry_run or not self.api_key:
            reason = "dry-run" if self.dry_run else "no API key"
            logger.info(f"Using placeholder generation ({reason})")
            return self._generate_placeholder(request)

        try:
            return self._call_api(request)
        except Exception as e:
            logger.error(f"Google Imagen generation failed: {e}")
            logger.info("Falling back to placeholder generation")
            return self._generate_placeholder(request, error_msg=str(e))

    def _call_api(self, request: GenerationRequest) -> GenerationResult:
        """Call the Google Imagen API."""
        self._init_client()

        from google.genai.types import GenerateImagesConfig

        logger.info(f"Calling Google Imagen API with model: {self.model_name}")

        # Generate the image
        response = self._client.models.generate_images(
            model=self.model_name,
            prompt=request.prompt,
            config=GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio=self._get_aspect_ratio(request.width, request.height),
            )
        )

        if not response.generated_images:
            raise RuntimeError("No images generated by Google Imagen")

        # Get the first generated image
        generated_image = response.generated_images[0]

        # Convert to PIL Image
        image_bytes = generated_image.image.image_bytes
        pil_image = Image.open(BytesIO(image_bytes)).convert("RGB")

        # Resize to requested dimensions if needed
        if pil_image.size != (request.width, request.height):
            pil_image = self._resize_and_crop(pil_image, request.width, request.height)

        logger.info(f"Successfully generated image: {pil_image.size}")

        return GenerationResult(
            image=pil_image,
            prompt_used=request.prompt,
            seed_used=request.seed,
            metadata={
                "model": self.model_name,
                "api": "google-genai",
            },
        )

    def _get_aspect_ratio(self, width: int, height: int) -> str:
        """Convert dimensions to Imagen aspect ratio string."""
        ratio = width / height

        # Imagen supported aspect ratios
        if abs(ratio - 1.0) < 0.1:
            return "1:1"
        elif abs(ratio - 16/9) < 0.1:
            return "16:9"
        elif abs(ratio - 9/16) < 0.1:
            return "9:16"
        elif abs(ratio - 4/3) < 0.1:
            return "4:3"
        elif abs(ratio - 3/4) < 0.1:
            return "3:4"
        else:
            return "1:1"

    def _resize_and_crop(
        self, image: Image.Image, target_width: int, target_height: int
    ) -> Image.Image:
        """Resize and center-crop image to target dimensions."""
        img_ratio = image.width / image.height
        target_ratio = target_width / target_height

        if img_ratio > target_ratio:
            new_height = target_height
            new_width = int(new_height * img_ratio)
        else:
            new_width = target_width
            new_height = int(new_width / img_ratio)

        resized = image.resize((new_width, new_height), Image.Resampling.LANCZOS)

        left = (new_width - target_width) // 2
        top = (new_height - target_height) // 2
        cropped = resized.crop((left, top, left + target_width, top + target_height))

        return cropped

    def _generate_placeholder(
        self, request: GenerationRequest, error_msg: Optional[str] = None
    ) -> GenerationResult:
        """Generate a placeholder image with prompt text."""
        from PIL import ImageDraw, ImageFont

        img = Image.new("RGB", (request.width, request.height))
        draw = ImageDraw.Draw(img)

        # Gradient background (Google colors)
        for y in range(request.height):
            r = int(66 + (y / request.height) * 50)
            g = int(133 + (y / request.height) * 30)
            b = int(244 - (y / request.height) * 40)
            draw.line([(0, y), (request.width, y)], fill=(r, g, b))

        # Placeholder silhouette
        cx, cy = request.width // 2, request.height // 2
        head_r = min(request.width, request.height) // 10

        draw.ellipse(
            [cx - head_r, cy - head_r * 3, cx + head_r, cy - head_r],
            fill=(220, 220, 240),
        )
        draw.rounded_rectangle(
            [cx - head_r, cy - head_r, cx + head_r, cy + head_r * 2],
            radius=8,
            fill=(200, 200, 220),
        )

        # Add text
        try:
            font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 12)
        except (OSError, IOError):
            try:
                font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 12)
            except (OSError, IOError):
                font = ImageFont.load_default()

        status = "DRY RUN" if self.dry_run else "NO API KEY"
        if error_msg:
            status = f"ERROR: {error_msg[:30]}"

        header = f"[GOOGLE IMAGEN - {status}]"
        draw.text((10, 10), header, font=font, fill=(255, 255, 255))

        # Wrap and display prompt
        prompt_lines = []
        words = request.prompt.split()
        current_line = ""
        for word in words:
            if len(current_line + " " + word) < 50:
                current_line = (current_line + " " + word).strip()
            else:
                prompt_lines.append(current_line)
                current_line = word
        if current_line:
            prompt_lines.append(current_line)

        y_pos = 35
        for line in prompt_lines[:10]:
            draw.text((10, y_pos), line, font=font, fill=(255, 255, 255, 200))
            y_pos += 16

        return GenerationResult(
            image=img,
            prompt_used=request.prompt,
            seed_used=request.seed,
            metadata={"mode": "placeholder", "reason": status.lower()},
        )


def get_google_adapter(
    api_key: Optional[str] = None,
    dry_run: bool = False,
) -> GoogleImagenAdapter:
    """Factory function to create a Google Imagen adapter."""
    return GoogleImagenAdapter(api_key=api_key, dry_run=dry_run)
